### ISSUE TITLE
Resource title must be a String, not Hash

### ISSUE THREAD

**Issue by michaelward82** [pro-vagrant/puppet-php_phars#8]
I get Resource title must be a String, not Hash at /tmp/vagrant-puppet-4/modules-0/php_phars/manifests/init.pp:114 on node precise64 when I use this module with puppet 2.7.19 under Vagrant.

Any ideas what is wrong?

**Comment by gajdaw** [comment]
That's strange. This module requires Puppet 3.x (here is the excerpt from `metadata.json`):

```
 {
"name": "puppet",
"version_requirement": "3.x"
}
```
I would expect some other message, something like `Unsupported Puppet version`.
Anyway, to use this module you have to upgrade Puppet to version 3. You can do this with:

https://forge.puppetlabs.com/gajdaw/puppet

**Comment by gajdaw** [comment]
@michaelward82 Michael, thanks for this report. I reproduced your error. As I suspected: your puppet needs to be updated. You can do it within ssh shell with:

    sudo puppet module install gajdaw-puppet
    sudo puppet apply -e "include puppet"

Alternatively, you can add `gajdaw/puppet` module to your `puppet/modules` directory in your project and add:

    include puppet

in your manifest.

**Comment by michaelward82** [comment]
Ok, this has helped. Thanks.
